version: '3'

services:
  composer:
    image: composer:latest
    working_dir: /var/www/file-get-contents
    volumes:
      - ./:/var/www/file-get-contents

  tests:
    image: php:7.0.33-cli
    working_dir: /var/www/file-get-contents
    volumes:
      - ./:/var/www/file-get-contents
    command: ./vendor/bin/phpunit --bootstrap vendor/autoload.php tests/SimpleHttpClientTest
